define([], function () {
    var departCities = {
        "hotCity": [{
            "countryId": 1,
            "ename": "beijing",
            "hotFlag": 2,
            "id": 1,
            "initial": "B",
            "jp": "bj",
            "name": "北京",
            "py": "beijing"
        }, {
            "countryId": 1,
            "ename": "shanghai",
            "hotFlag": 1,
            "id": 2,
            "initial": "S",
            "jp": "sh",
            "name": "上海",
            "py": "shanghai"
        }, {
            "countryId": 1,
            "ename": "tianjin",
            "hotFlag": 305,
            "id": 3,
            "initial": "T",
            "jp": "tj",
            "name": "天津",
            "py": "tianjin"
        },{
            "countryId": 1,
            "ename": "qingdao",
            "hotFlag": 250,
            "id": 7,
            "initial": "Q",
            "jp": "qd",
            "name": "青岛",
            "py": "qingdao"
        }, {
            "countryId": 1,
            "ename": "nanjing",
            "hotFlag": 5,
            "id": 12,
            "initial": "N",
            "jp": "nj",
            "name": "南京",
            "py": "nanjing"
        }, {
            "countryId": 1,
            "ename": "hangzhou",
            "hotFlag": 6,
            "id": 17,
            "initial": "H",
            "jp": "hz",
            "name": "杭州",
            "py": "hangzhou"
        }, {
            "countryId": 1,
            "ename": "xiamen",
            "hotFlag": 350,
            "id": 25,
            "initial": "X",
            "jp": "xm",
            "name": "厦门",
            "py": "xiamen"
        }, {
            "countryId": 1,
            "ename": "chengdu",
            "hotFlag": 7,
            "id": 28,
            "initial": "C",
            "jp": "cd",
            "name": "成都",
            "py": "chengdu"
        }, {
            "countryId": 1,
            "ename": "shenzhen",
            "hotFlag": 3,
            "id": 30,
            "initial": "S",
            "jp": "sz",
            "name": "深圳",
            "py": "shenzhen"
        }, {
            "countryId": 1,
            "ename": "guangzhou",
            "hotFlag": 4,
            "id": 32,
            "initial": "G",
            "jp": "gz",
            "name": "广州",
            "py": "guangzhou"
        }, {
            "countryId": 1,
            "ename": "shenyang",
            "hotFlag": 280,
            "id": 451,
            "initial": "S",
            "jp": "sy",
            "name": "沈阳",
            "py": "shenyang"
        }, {
            "countryId": 1,
            "ename": "wuhan",
            "hotFlag": 8,
            "id": 477,
            "initial": "W",
            "jp": "wh",
            "name": "武汉",
            "py": "wuhan"
        }],
        "pySort": [{
            "countryId": 1,
            "ename": "baotou",
            "hotFlag": 105,
            "id": 141,
            "initial": "B",
            "jp": "bt",
            "name": "包头",
            "py": "baotou"
        }, {
            "countryId": 1,
            "ename": "beijing",
            "hotFlag": 110,
            "id": 1,
            "initial": "B",
            "jp": "bj",
            "name": "北京",
            "py": "beijing"
        },  {
            "countryId": 1,
            "ename": "changchun",
            "hotFlag": 115,
            "id": 158,
            "initial": "C",
            "jp": "cc",
            "name": "长春",
            "py": "changchun"
        }, {
            "countryId": 1,
            "ename": "changsha",
            "hotFlag": 120,
            "id": 206,
            "initial": "C",
            "jp": "cs",
            "name": "长沙",
            "py": "changsha"
        }, {
            "countryId": 1,
            "ename": "changzhou",
            "hotFlag": 125,
            "id": 213,
            "initial": "C",
            "jp": "cz",
            "name": "常州",
            "py": "changzhou"
        }, {
            "countryId": 1,
            "ename": "chengdu",
            "hotFlag": 130,
            "id": 28,
            "initial": "C",
            "jp": "cd",
            "name": "成都",
            "py": "chengdu"
        },  {
            "countryId": 1,
            "ename": "chongqing",
            "hotFlag": 131,
            "id": 4,
            "initial": "C",
            "jp": "cq",
            "name": "重庆",
            "py": "chongqing"
        }, {
            "countryId": 1,
            "ename": "dalian",
            "hotFlag": 135,
            "id": 6,
            "initial": "D",
            "jp": "dl",
            "name": "大连",
            "py": "dalian"
        }, {
            "countryId": 1,
            "ename": "dongguan",
            "hotFlag": 140,
            "id": 223,
            "initial": "D",
            "jp": "dw",
            "name": "东莞",
            "py": "dongguan"
        }, {
            "countryId": 1,
            "ename": "foshan",
            "hotFlag": 145,
            "id": 251,
            "initial": "F",
            "jp": "fs",
            "name": "佛山",
            "py": "foshan"
        }, {
            "countryId": 1,
            "ename": "fuzhou",
            "hotFlag": 150,
            "id": 258,
            "initial": "F",
            "jp": "fz",
            "name": "福州",
            "py": "fuzhou"
        },  {
            "countryId": 1,
            "ename": "guangzhou",
            "hotFlag": 155,
            "id": 32,
            "initial": "G",
            "jp": "gz",
            "name": "广州",
            "py": "guangzhou"
        }, {
            "countryId": 1,
            "ename": "guiyang",
            "hotFlag": 160,
            "id": 38,
            "initial": "G",
            "jp": "gy",
            "name": "贵阳",
            "py": "guiyang"
        }, {
            "countryId": 1,
            "ename": "haerbin",
            "hotFlag": 165,
            "id": 5,
            "initial": "H",
            "jp": "heb",
            "name": "哈尔滨",
            "py": "haerbin"
        }, {
            "countryId": 1,
            "ename": "haikou",
            "hotFlag": 170,
            "id": 42,
            "initial": "H",
            "jp": "hk",
            "name": "海口",
            "py": "haikou"
        }, {
            "countryId": 1,
            "ename": "hailaer",
            "hotFlag": 175,
            "id": 142,
            "initial": "H",
            "jp": "hle",
            "name": "海拉尔",
            "py": "hailaer"
        }, {
            "countryId": 1,
            "ename": "hangzhou",
            "hotFlag": 180,
            "id": 17,
            "initial": "H",
            "jp": "hz",
            "name": "杭州",
            "py": "hangzhou"
        }, {
            "countryId": 1,
            "ename": "hefei",
            "hotFlag": 185,
            "id": 278,
            "initial": "H",
            "jp": "hf",
            "name": "合肥",
            "py": "hefei"
        },  {
            "countryId": 1,
            "ename": "huhehaote",
            "hotFlag": 190,
            "id": 103,
            "initial": "H",
            "jp": "hhht",
            "name": "呼和浩特",
            "py": "huhehaote"
        }, {
            "countryId": 1,
            "ename": "jiangmen",
            "hotFlag": 200,
            "id": 316,
            "initial": "J",
            "jp": "jm",
            "name": "江门",
            "py": "jiangmen"
        },   {
            "countryId": 1,
            "ename": "jinan",
            "hotFlag": 195,
            "id": 144,
            "initial": "J",
            "jp": "jn",
            "name": "济南",
            "py": "jinan"
        },  {
            "countryId": 1,
            "ename": "kashi",
            "hotFlag": 205,
            "id": 109,
            "initial": "K",
            "jp": "kss",
            "name": "喀什市",
            "py": "kashi"
        }, {
            "countryId": 1,
            "ename": "kunming",
            "hotFlag": 210,
            "id": 34,
            "initial": "K",
            "jp": "km",
            "name": "昆明",
            "py": "kunming"
        }, {
            "countryId": 1,
            "ename": "lanzhou",
            "hotFlag": 220,
            "id": 100,
            "initial": "L",
            "jp": "lz",
            "name": "兰州",
            "py": "lanzhou"
        }, {
            "countryId": 1,
            "ename": "lasa",
            "hotFlag": 215,
            "id": 41,
            "initial": "L",
            "jp": "ls",
            "name": "拉萨",
            "py": "lasa"
        },  {
            "countryId": 1,
            "ename": "mianyang",
            "hotFlag": 225,
            "id": 370,
            "initial": "M",
            "jp": "my",
            "name": "绵阳",
            "py": "mianyang"
        }, {
            "countryId": 1,
            "ename": "nanchang",
            "hotFlag": 230,
            "id": 376,
            "initial": "N",
            "jp": "nc",
            "name": "南昌",
            "py": "nanchang"
        }, {
            "countryId": 1,
            "ename": "nanjing",
            "hotFlag": 235,
            "id": 12,
            "initial": "N",
            "jp": "nj",
            "name": "南京",
            "py": "nanjing"
        }, {
            "countryId": 1,
            "ename": "nanning",
            "hotFlag": 240,
            "id": 380,
            "initial": "N",
            "jp": "nn",
            "name": "南宁",
            "py": "nanning"
        }, {
            "countryId": 1,
            "ename": "nantong",
            "hotFlag": 241,
            "id": 82,
            "initial": "N",
            "jp": "nt",
            "name": "南通",
            "py": "nantong"
        }, {
            "countryId": 1,
            "ename": "ningbo",
            "hotFlag": 245,
            "id": 375,
            "initial": "N",
            "jp": "nb",
            "name": "宁波",
            "py": "ningbo"
        }, {
            "countryId": 1,
            "ename": "qingdao",
            "hotFlag": 250,
            "id": 7,
            "initial": "Q",
            "jp": "qd",
            "name": "青岛",
            "py": "qingdao"
        }, {
            "countryId": 1,
            "ename": "quanzhou",
            "hotFlag": 255,
            "id": 406,
            "initial": "Q",
            "jp": "qz",
            "name": "泉州",
            "py": "quanzhou"
        }, {
            "countryId": 1,
            "ename": "sanya",
            "hotFlag": 260,
            "id": 43,
            "initial": "S",
            "jp": "sy",
            "name": "三亚",
            "py": "sanya"
        }, {
            "countryId": 1,
            "ename": "shanghai",
            "hotFlag": 270,
            "id": 2,
            "initial": "S",
            "jp": "sh",
            "name": "上海",
            "py": "shanghai"
        }, {
            "countryId": 1,
            "ename": "shantou",
            "hotFlag": 265,
            "id": 447,
            "initial": "S",
            "jp": "st",
            "name": "汕头",
            "py": "shantou"
        }, {
            "countryId": 1,
            "ename": "shenyang",
            "hotFlag": 280,
            "id": 451,
            "initial": "S",
            "jp": "sy",
            "name": "沈阳",
            "py": "shenyang"
        }, {
            "countryId": 1,
            "ename": "shenzhen",
            "hotFlag": 275,
            "id": 30,
            "initial": "S",
            "jp": "sz",
            "name": "深圳",
            "py": "shenzhen"
        }, {
            "countryId": 1,
            "ename": "shijiazhuang",
            "hotFlag": 285,
            "id": 428,
            "initial": "S",
            "jp": "sjz",
            "name": "石家庄",
            "py": "shijiazhuang"
        }, {
            "countryId": 1,
            "ename": "suzhou",
            "hotFlag": 290,
            "id": 14,
            "initial": "S",
            "jp": "sz",
            "name": "苏州",
            "py": "suzhou"
        },  {
            "countryId": 1,
            "ename": "taiyuan",
            "hotFlag": 300,
            "id": 105,
            "initial": "T",
            "jp": "ty",
            "name": "太原",
            "py": "taiyuan"
        }, {
            "countryId": 1,
            "ename": "taizhou",
            "hotFlag": 295,
            "id": 578,
            "initial": "T",
            "jp": "tz",
            "name": "台州",
            "py": "taizhou"
        }, {
            "countryId": 1,
            "ename": "tianjin",
            "hotFlag": 305,
            "id": 3,
            "initial": "T",
            "jp": "tj",
            "name": "天津",
            "py": "tianjin"
        }, {
            "countryId": 1,
            "ename": "weihai",
            "hotFlag": 310,
            "id": 479,
            "initial": "W",
            "jp": "wh",
            "name": "威海",
            "py": "weihai"
        }, {
            "countryId": 1,
            "ename": "wenzhou",
            "hotFlag": 315,
            "id": 491,
            "initial": "W",
            "jp": "wz",
            "name": "温州",
            "py": "wenzhou"
        }, {
            "countryId": 1,
            "ename": "wuhan",
            "hotFlag": 330,
            "id": 477,
            "initial": "W",
            "jp": "wh",
            "name": "武汉",
            "py": "wuhan"
        }, {
            "countryId": 1,
            "ename": "wulumuqi",
            "hotFlag": 320,
            "id": 39,
            "initial": "W",
            "jp": "wlmq",
            "name": "乌鲁木齐",
            "py": "wulumuqi"
        }, {
            "countryId": 1,
            "ename": "wuxi",
            "hotFlag": 325,
            "id": 13,
            "initial": "W",
            "jp": "wx",
            "name": "无锡",
            "py": "wuxi"
        },  {
            "countryId": 1,
            "ename": "xiamen",
            "hotFlag": 350,
            "id": 25,
            "initial": "X",
            "jp": "xm",
            "name": "厦门",
            "py": "xiamen"
        },  {
            "countryId": 1,
            "ename": "xian",
            "hotFlag": 335,
            "id": 10,
            "initial": "X",
            "jp": "xa",
            "name": "西安",
            "py": "xian"
        }, {
            "countryId": 1,
            "ename": "xichang",
            "hotFlag": 340,
            "id": 494,
            "initial": "X",
            "jp": "xc",
            "name": "西昌",
            "py": "xichang"
        }, {
            "countryId": 1,
            "ename": "xining",
            "hotFlag": 345,
            "id": 124,
            "initial": "X",
            "jp": "xn",
            "name": "西宁",
            "py": "xining"
        },  {
            "countryId": 1,
            "ename": "xuzhou",
            "hotFlag": 360,
            "id": 512,
            "initial": "X",
            "jp": "xz",
            "name": "徐州",
            "py": "xuzhou"
        },   {
            "countryId": 1,
            "ename": "yanji",
            "hotFlag": 370,
            "id": 523,
            "initial": "Y",
            "jp": "yj",
            "name": "延吉",
            "py": "yanji"
        }, {
            "countryId": 1,
            "ename": "yantai",
            "hotFlag": 365,
            "id": 533,
            "initial": "Y",
            "jp": "yt",
            "name": "烟台",
            "py": "yantai"
        },  {
            "countryId": 1,
            "ename": "yinchuan",
            "hotFlag": 380,
            "id": 99,
            "initial": "Y",
            "jp": "yc",
            "name": "银川",
            "py": "yinchuan"
        }, {
            "countryId": 1,
            "ename": "yiwu",
            "hotFlag": 375,
            "id": 536,
            "initial": "Y",
            "jp": "yw",
            "name": "义乌",
            "py": "yiwu"
        }, {
            "countryId": 1,
            "ename": "yulin",
            "hotFlag": 385,
            "id": 527,
            "initial": "Y",
            "jp": "yl",
            "name": "榆林",
            "py": "yulin"
        }, {
            "countryId": 1,
            "ename": "yuncheng",
            "hotFlag": 390,
            "id": 140,
            "initial": "Y",
            "jp": "yc",
            "name": "运城",
            "py": "yuncheng"
        },  {
            "countryId": 1,
            "ename": "zhengzhou",
            "hotFlag": 395,
            "id": 559,
            "initial": "Z",
            "jp": "zz",
            "name": "郑州",
            "py": "zhengzhou"
        }, {
            "countryId": 1,
            "ename": "zhongshan",
            "hotFlag": 400,
            "id": 553,
            "initial": "Z",
            "jp": "zs",
            "name": "中山",
            "py": "zhongshan"
        },  {
            "countryId": 1,
            "ename": "zhuhai",
            "hotFlag": 410,
            "id": 31,
            "initial": "Z",
            "jp": "zh",
            "name": "珠海",
            "py": "zhuhai"
        }],
        "Alphabet": [{
            "initial": "B",
            "data": [ {
                "countryId": 1,
                "ename": "beijing",
                "hotFlag": 110,
                "id": 1,
                "initial": "B",
                "jp": "bj",
                "name": "北京",
                "py": "beijing"
            }, {
                "countryId": 1,
                "ename": "baotou",
                "hotFlag": 105,
                "id": 141,
                "initial": "B",
                "jp": "bt",
                "name": "包头",
                "py": "baotou"
            }]
        }, {
            "initial": "C",
            "data": [{
                "countryId": 1,
                "ename": "chongqing",
                "hotFlag": 131,
                "id": 4,
                "initial": "C",
                "jp": "cq",
                "name": "重庆",
                "py": "chongqing"
            }, {
                "countryId": 1,
                "ename": "chengdu",
                "hotFlag": 130,
                "id": 28,
                "initial": "C",
                "jp": "cd",
                "name": "成都",
                "py": "chengdu"
            }, {
                "countryId": 1,
                "ename": "changchun",
                "hotFlag": 115,
                "id": 158,
                "initial": "C",
                "jp": "cc",
                "name": "长春",
                "py": "changchun"
            }, {
                "countryId": 1,
                "ename": "changsha",
                "hotFlag": 120,
                "id": 206,
                "initial": "C",
                "jp": "cs",
                "name": "长沙",
                "py": "changsha"
            }, {
                "countryId": 1,
                "ename": "changzhou",
                "hotFlag": 125,
                "id": 213,
                "initial": "C",
                "jp": "cz",
                "name": "常州",
                "py": "changzhou"
            }]
        }, {
            "initial": "D",
            "data": [{
                "countryId": 1,
                "ename": "dalian",
                "hotFlag": 135,
                "id": 6,
                "initial": "D",
                "jp": "dl",
                "name": "大连",
                "py": "dalian"
            }, {
                "countryId": 1,
                "ename": "dongguan",
                "hotFlag": 140,
                "id": 223,
                "initial": "D",
                "jp": "dw",
                "name": "东莞",
                "py": "dongguan"
            }]
        }, {
            "initial": "F",
            "data": [{
                "countryId": 1,
                "ename": "foshan",
                "hotFlag": 145,
                "id": 251,
                "initial": "F",
                "jp": "fs",
                "name": "佛山",
                "py": "foshan"
            }, {
                "countryId": 1,
                "ename": "fuzhou",
                "hotFlag": 150,
                "id": 258,
                "initial": "F",
                "jp": "fz",
                "name": "福州",
                "py": "fuzhou"
            }]
        }, {
            "initial": "G",
            "data": [{
                "countryId": 1,
                "ename": "guangzhou",
                "hotFlag": 155,
                "id": 32,
                "initial": "G",
                "jp": "gz",
                "name": "广州",
                "py": "guangzhou"
            }, {
                "countryId": 1,
                "ename": "guiyang",
                "hotFlag": 160,
                "id": 38,
                "initial": "G",
                "jp": "gy",
                "name": "贵阳",
                "py": "guiyang"
            }]
        }, {
            "initial": "H",
            "data": [{
                "countryId": 1,
                "ename": "haerbin",
                "hotFlag": 165,
                "id": 5,
                "initial": "H",
                "jp": "heb",
                "name": "哈尔滨",
                "py": "haerbin"
            }, {
                "countryId": 1,
                "ename": "hangzhou",
                "hotFlag": 180,
                "id": 17,
                "initial": "H",
                "jp": "hz",
                "name": "杭州",
                "py": "hangzhou"
            }, {
                "countryId": 1,
                "ename": "haikou",
                "hotFlag": 170,
                "id": 42,
                "initial": "H",
                "jp": "hk",
                "name": "海口",
                "py": "haikou"
            }, {
                "countryId": 1,
                "ename": "huhehaote",
                "hotFlag": 190,
                "id": 103,
                "initial": "H",
                "jp": "hhht",
                "name": "呼和浩特",
                "py": "huhehaote"
            }, {
                "countryId": 1,
                "ename": "hailaer",
                "hotFlag": 175,
                "id": 142,
                "initial": "H",
                "jp": "hle",
                "name": "海拉尔",
                "py": "hailaer"
            }, {
                "countryId": 1,
                "ename": "hefei",
                "hotFlag": 185,
                "id": 278,
                "initial": "H",
                "jp": "hf",
                "name": "合肥",
                "py": "hefei"
            }]
        }, {
            "initial": "J",
            "data": [{
                "countryId": 1,
                "ename": "jinan",
                "hotFlag": 195,
                "id": 144,
                "initial": "J",
                "jp": "jn",
                "name": "济南",
                "py": "jinan"
            }, {
                "countryId": 1,
                "ename": "jiangmen",
                "hotFlag": 200,
                "id": 316,
                "initial": "J",
                "jp": "jm",
                "name": "江门",
                "py": "jiangmen"
            }]
        }, {
            "initial": "K",
            "data": [ {
                "countryId": 1,
                "ename": "kunming",
                "hotFlag": 210,
                "id": 34,
                "initial": "K",
                "jp": "km",
                "name": "昆明",
                "py": "kunming"
            },{
                "countryId": 1,
                "ename": "kashi",
                "hotFlag": 205,
                "id": 109,
                "initial": "K",
                "jp": "kss",
                "name": "喀什市",
                "py": "kashi"
            }]
        }, {
            "initial": "L",
            "data": [{
                "countryId": 1,
                "ename": "lasa",
                "hotFlag": 215,
                "id": 41,
                "initial": "L",
                "jp": "ls",
                "name": "拉萨",
                "py": "lasa"
            }, {
                "countryId": 1,
                "ename": "lanzhou",
                "hotFlag": 220,
                "id": 100,
                "initial": "L",
                "jp": "lz",
                "name": "兰州",
                "py": "lanzhou"
            }]
        }, {
            "initial": "M",
            "data": [{
                "countryId": 1,
                "ename": "mianyang",
                "hotFlag": 225,
                "id": 370,
                "initial": "M",
                "jp": "my",
                "name": "绵阳",
                "py": "mianyang"
            }]
        }, {
            "initial": "N",
            "data": [{
                "countryId": 1,
                "ename": "nanjing",
                "hotFlag": 235,
                "id": 12,
                "initial": "N",
                "jp": "nj",
                "name": "南京",
                "py": "nanjing"
            }, {
                "countryId": 1,
                "ename": "nantong",
                "hotFlag": 241,
                "id": 82,
                "initial": "N",
                "jp": "nt",
                "name": "南通",
                "py": "nantong"
            }, {
                "countryId": 1,
                "ename": "ningbo",
                "hotFlag": 245,
                "id": 375,
                "initial": "N",
                "jp": "nb",
                "name": "宁波",
                "py": "ningbo"
            }, {
                "countryId": 1,
                "ename": "nanchang",
                "hotFlag": 230,
                "id": 376,
                "initial": "N",
                "jp": "nc",
                "name": "南昌",
                "py": "nanchang"
            },  {
                "countryId": 1,
                "ename": "nanning",
                "hotFlag": 240,
                "id": 380,
                "initial": "N",
                "jp": "nn",
                "name": "南宁",
                "py": "nanning"
            }]
        }, {
            "initial": "Q",
            "data": [{
                "countryId": 1,
                "ename": "qingdao",
                "hotFlag": 250,
                "id": 7,
                "initial": "Q",
                "jp": "qd",
                "name": "青岛",
                "py": "qingdao"
            }, {
                "countryId": 1,
                "ename": "quanzhou",
                "hotFlag": 255,
                "id": 406,
                "initial": "Q",
                "jp": "qz",
                "name": "泉州",
                "py": "quanzhou"
            }]
        }, {
            "initial": "S",
            "data": [{
                "countryId": 1,
                "ename": "shanghai",
                "hotFlag": 270,
                "id": 2,
                "initial": "S",
                "jp": "sh",
                "name": "上海",
                "py": "shanghai"
            }, {
                "countryId": 1,
                "ename": "suzhou",
                "hotFlag": 290,
                "id": 14,
                "initial": "S",
                "jp": "sz",
                "name": "苏州",
                "py": "suzhou"
            }, {
                "countryId": 1,
                "ename": "shenzhen",
                "hotFlag": 275,
                "id": 30,
                "initial": "S",
                "jp": "sz",
                "name": "深圳",
                "py": "shenzhen"
            }, {
                "countryId": 1,
                "ename": "sanya",
                "hotFlag": 260,
                "id": 43,
                "initial": "S",
                "jp": "sy",
                "name": "三亚",
                "py": "sanya"
            }, {
                "countryId": 1,
                "ename": "shijiazhuang",
                "hotFlag": 285,
                "id": 428,
                "initial": "S",
                "jp": "sjz",
                "name": "石家庄",
                "py": "shijiazhuang"
            }, {
                "countryId": 1,
                "ename": "shantou",
                "hotFlag": 265,
                "id": 447,
                "initial": "S",
                "jp": "st",
                "name": "汕头",
                "py": "shantou"
            },  {
                "countryId": 1,
                "ename": "shenyang",
                "hotFlag": 280,
                "id": 451,
                "initial": "S",
                "jp": "sy",
                "name": "沈阳",
                "py": "shenyang"
            }]
        }, {
            "initial": "T",
            "data": [{
                "countryId": 1,
                "ename": "tianjin",
                "hotFlag": 305,
                "id": 3,
                "initial": "T",
                "jp": "tj",
                "name": "天津",
                "py": "tianjin"
            }, {
                "countryId": 1,
                "ename": "taiyuan",
                "hotFlag": 300,
                "id": 105,
                "initial": "T",
                "jp": "ty",
                "name": "太原",
                "py": "taiyuan"
            }, {
                "countryId": 1,
                "ename": "taizhou",
                "hotFlag": 295,
                "id": 578,
                "initial": "T",
                "jp": "tz",
                "name": "台州",
                "py": "taizhou"
            }]
        }, {
            "initial": "W",
            "data": [{
                "countryId": 1,
                "ename": "wuxi",
                "hotFlag": 325,
                "id": 13,
                "initial": "W",
                "jp": "wx",
                "name": "无锡",
                "py": "wuxi"
            }, {
                "countryId": 1,
                "ename": "wulumuqi",
                "hotFlag": 320,
                "id": 39,
                "initial": "W",
                "jp": "wlmq",
                "name": "乌鲁木齐",
                "py": "wulumuqi"
            }, {
                "countryId": 1,
                "ename": "wuhan",
                "hotFlag": 330,
                "id": 477,
                "initial": "W",
                "jp": "wh",
                "name": "武汉",
                "py": "wuhan"
            }, {
                "countryId": 1,
                "ename": "weihai",
                "hotFlag": 310,
                "id": 479,
                "initial": "W",
                "jp": "wh",
                "name": "威海",
                "py": "weihai"
            }, {
                "countryId": 1,
                "ename": "wenzhou",
                "hotFlag": 315,
                "id": 491,
                "initial": "W",
                "jp": "wz",
                "name": "温州",
                "py": "wenzhou"
            }]
        }, {
            "initial": "X",
            "data": [{
                "countryId": 1,
                "ename": "xian",
                "hotFlag": 335,
                "id": 10,
                "initial": "X",
                "jp": "xa",
                "name": "西安",
                "py": "xian"
            },  {
                "countryId": 1,
                "ename": "xiamen",
                "hotFlag": 350,
                "id": 25,
                "initial": "X",
                "jp": "xm",
                "name": "厦门",
                "py": "xiamen"
            }, {
                "countryId": 1,
                "ename": "xining",
                "hotFlag": 345,
                "id": 124,
                "initial": "X",
                "jp": "xn",
                "name": "西宁",
                "py": "xining"
            }, {
                "countryId": 1,
                "ename": "xichang",
                "hotFlag": 340,
                "id": 494,
                "initial": "X",
                "jp": "xc",
                "name": "西昌",
                "py": "xichang"
            }, {
                "countryId": 1,
                "ename": "xuzhou",
                "hotFlag": 360,
                "id": 512,
                "initial": "X",
                "jp": "xz",
                "name": "徐州",
                "py": "xuzhou"
            }]
        }, {
            "initial": "Y",
            "data": [{
                "countryId": 1,
                "ename": "yinchuan",
                "hotFlag": 380,
                "id": 99,
                "initial": "Y",
                "jp": "yc",
                "name": "银川",
                "py": "yinchuan"
            }, {
                "countryId": 1,
                "ename": "yuncheng",
                "hotFlag": 390,
                "id": 140,
                "initial": "Y",
                "jp": "yc",
                "name": "运城",
                "py": "yuncheng"
            }, {
                "countryId": 1,
                "ename": "yanji",
                "hotFlag": 370,
                "id": 523,
                "initial": "Y",
                "jp": "yj",
                "name": "延吉",
                "py": "yanji"
            }, {
                "countryId": 1,
                "ename": "yulin",
                "hotFlag": 385,
                "id": 527,
                "initial": "Y",
                "jp": "yl",
                "name": "榆林",
                "py": "yulin"
            }, {
                "countryId": 1,
                "ename": "yantai",
                "hotFlag": 365,
                "id": 533,
                "initial": "Y",
                "jp": "yt",
                "name": "烟台",
                "py": "yantai"
            },  {
                "countryId": 1,
                "ename": "yiwu",
                "hotFlag": 375,
                "id": 536,
                "initial": "Y",
                "jp": "yw",
                "name": "义乌",
                "py": "yiwu"
            }]
        }, {
            "initial": "Z",
            "data": [{
                "countryId": 1,
                "ename": "zhuhai",
                "hotFlag": 410,
                "id": 31,
                "initial": "Z",
                "jp": "zh",
                "name": "珠海",
                "py": "zhuhai"
            }, {
                "countryId": 1,
                "ename": "zhongshan",
                "hotFlag": 400,
                "id": 553,
                "initial": "Z",
                "jp": "zs",
                "name": "中山",
                "py": "zhongshan"
            }, {
                "countryId": 1,
                "ename": "zhengzhou",
                "hotFlag": 395,
                "id": 559,
                "initial": "Z",
                "jp": "zz",
                "name": "郑州",
                "py": "zhengzhou"
            }]
        }]
    };
    return departCities;
});