//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace TravelOnline.tokiomarine {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ThirdPartyManagementBinding", Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryGOTApolicyInfoReturnType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryGOTApolicyInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendTravelBizType))]
    public partial class ThirdPartyManagement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendTravelBizOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryGOTApolicyInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ThirdPartyManagement() {
            this.Url = global::TravelOnline.Properties.Settings.Default.TravelOnline_tokiomarine_ThirdPartyManagement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendTravelBizCompletedEventHandler sendTravelBizCompleted;
        
        /// <remarks/>
        public event queryGOTApolicyInfoCompletedEventHandler queryGOTApolicyInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/soap/http", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendTravelBizResponse", Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
        public sendTravelBizResponseType sendTravelBiz([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")] sendTravelBizRequestType sendTravelBizRequest) {
            object[] results = this.Invoke("sendTravelBiz", new object[] {
                        sendTravelBizRequest});
            return ((sendTravelBizResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void sendTravelBizAsync(sendTravelBizRequestType sendTravelBizRequest) {
            this.sendTravelBizAsync(sendTravelBizRequest, null);
        }
        
        /// <remarks/>
        public void sendTravelBizAsync(sendTravelBizRequestType sendTravelBizRequest, object userState) {
            if ((this.sendTravelBizOperationCompleted == null)) {
                this.sendTravelBizOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendTravelBizOperationCompleted);
            }
            this.InvokeAsync("sendTravelBiz", new object[] {
                        sendTravelBizRequest}, this.sendTravelBizOperationCompleted, userState);
        }
        
        private void OnsendTravelBizOperationCompleted(object arg) {
            if ((this.sendTravelBizCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendTravelBizCompleted(this, new sendTravelBizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/soap/http", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryGOTApolicyInfoResponse", Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
        public queryGOTApolicyInfoResponseType queryGOTApolicyInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")] queryGOTApolicyInfoRequestType queryGOTApolicyInfoRequest) {
            object[] results = this.Invoke("queryGOTApolicyInfo", new object[] {
                        queryGOTApolicyInfoRequest});
            return ((queryGOTApolicyInfoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void queryGOTApolicyInfoAsync(queryGOTApolicyInfoRequestType queryGOTApolicyInfoRequest) {
            this.queryGOTApolicyInfoAsync(queryGOTApolicyInfoRequest, null);
        }
        
        /// <remarks/>
        public void queryGOTApolicyInfoAsync(queryGOTApolicyInfoRequestType queryGOTApolicyInfoRequest, object userState) {
            if ((this.queryGOTApolicyInfoOperationCompleted == null)) {
                this.queryGOTApolicyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryGOTApolicyInfoOperationCompleted);
            }
            this.InvokeAsync("queryGOTApolicyInfo", new object[] {
                        queryGOTApolicyInfoRequest}, this.queryGOTApolicyInfoOperationCompleted, userState);
        }
        
        private void OnqueryGOTApolicyInfoOperationCompleted(object arg) {
            if ((this.queryGOTApolicyInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryGOTApolicyInfoCompleted(this, new queryGOTApolicyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
    public partial class sendTravelBizRequestType : sendTravelBizType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendTravelBizRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class sendTravelBizType {
        
        private RequestRelatedType requestRelatedField;
        
        private ReferenceType referenceField;
        
        private PolicyBasicInfoType policyBasicInfoField;
        
        private InsuredType[] insuredListField;
        
        /// <remarks/>
        public RequestRelatedType RequestRelated {
            get {
                return this.requestRelatedField;
            }
            set {
                this.requestRelatedField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public PolicyBasicInfoType PolicyBasicInfo {
            get {
                return this.policyBasicInfoField;
            }
            set {
                this.policyBasicInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Insured", IsNullable=false)]
        public InsuredType[] InsuredList {
            get {
                return this.insuredListField;
            }
            set {
                this.insuredListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class RequestRelatedType {
        
        private string requestTypeField;
        
        private string userField;
        
        private string passwordField;
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class PolicyType {
        
        private PolicyBasicInfoType policyBasicInfoField;
        
        private InsuredType[] insuredListField;
        
        private string policyStatusField;
        
        /// <remarks/>
        public PolicyBasicInfoType PolicyBasicInfo {
            get {
                return this.policyBasicInfoField;
            }
            set {
                this.policyBasicInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Insured", IsNullable=false)]
        public InsuredType[] InsuredList {
            get {
                return this.insuredListField;
            }
            set {
                this.insuredListField = value;
            }
        }
        
        /// <remarks/>
        public string policyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class PolicyBasicInfoType {
        
        private string policyNOField;
        
        private string applicationNOField;
        
        private System.DateTime effectiveDateField;
        
        private bool effectiveDateFieldSpecified;
        
        private System.DateTime expireDateField;
        
        private bool expireDateFieldSpecified;
        
        private string productCodeField;
        
        private string currencyField;
        
        private double premiumField;
        
        private bool premiumFieldSpecified;
        
        private double suminsuredField;
        
        private bool suminsuredFieldSpecified;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.DateTime inputDateField;
        
        private bool inputDateFieldSpecified;
        
        /// <remarks/>
        public string policyNO {
            get {
                return this.policyNOField;
            }
            set {
                this.policyNOField = value;
            }
        }
        
        /// <remarks/>
        public string applicationNO {
            get {
                return this.applicationNOField;
            }
            set {
                this.applicationNOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectiveDateSpecified {
            get {
                return this.effectiveDateFieldSpecified;
            }
            set {
                this.effectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expireDateSpecified {
            get {
                return this.expireDateFieldSpecified;
            }
            set {
                this.expireDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public double premium {
            get {
                return this.premiumField;
            }
            set {
                this.premiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool premiumSpecified {
            get {
                return this.premiumFieldSpecified;
            }
            set {
                this.premiumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double suminsured {
            get {
                return this.suminsuredField;
            }
            set {
                this.suminsuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool suminsuredSpecified {
            get {
                return this.suminsuredFieldSpecified;
            }
            set {
                this.suminsuredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime inputDate {
            get {
                return this.inputDateField;
            }
            set {
                this.inputDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inputDateSpecified {
            get {
                return this.inputDateFieldSpecified;
            }
            set {
                this.inputDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class InsuredType {
        
        private string groupNoField;
        
        private string policyHolderFlagField;
        
        private string nameField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string genderField;
        
        private string addressField;
        
        private string insuredRelationField;
        
        private string postcodeField;
        
        private string planCodeField;
        
        private double premiumPerPeopleField;
        
        private bool premiumPerPeopleFieldSpecified;
        
        private string mainDestinationField;
        
        private string travelPurposeField;
        
        private System.DateTime travelDurationStartField;
        
        private bool travelDurationStartFieldSpecified;
        
        private System.DateTime travelDurationEndField;
        
        private bool travelDurationEndFieldSpecified;
        
        /// <remarks/>
        public string groupNo {
            get {
                return this.groupNoField;
            }
            set {
                this.groupNoField = value;
            }
        }
        
        /// <remarks/>
        public string policyHolderFlag {
            get {
                return this.policyHolderFlagField;
            }
            set {
                this.policyHolderFlagField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string insuredRelation {
            get {
                return this.insuredRelationField;
            }
            set {
                this.insuredRelationField = value;
            }
        }
        
        /// <remarks/>
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string planCode {
            get {
                return this.planCodeField;
            }
            set {
                this.planCodeField = value;
            }
        }
        
        /// <remarks/>
        public double PremiumPerPeople {
            get {
                return this.premiumPerPeopleField;
            }
            set {
                this.premiumPerPeopleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumPerPeopleSpecified {
            get {
                return this.premiumPerPeopleFieldSpecified;
            }
            set {
                this.premiumPerPeopleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MainDestination {
            get {
                return this.mainDestinationField;
            }
            set {
                this.mainDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string TravelPurpose {
            get {
                return this.travelPurposeField;
            }
            set {
                this.travelPurposeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TravelDurationStart {
            get {
                return this.travelDurationStartField;
            }
            set {
                this.travelDurationStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelDurationStartSpecified {
            get {
                return this.travelDurationStartFieldSpecified;
            }
            set {
                this.travelDurationStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TravelDurationEnd {
            get {
                return this.travelDurationEndField;
            }
            set {
                this.travelDurationEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelDurationEndSpecified {
            get {
                return this.travelDurationEndFieldSpecified;
            }
            set {
                this.travelDurationEndFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryGOTApolicyInfoResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class queryGOTApolicyInfoReturnType {
        
        private string requestTypeField;
        
        private string responseCodeField;
        
        private PolicyType policyField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public PolicyType Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
    public partial class queryGOTApolicyInfoResponseType : queryGOTApolicyInfoReturnType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryGOTApolicyInfoRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class queryGOTApolicyInfoType {
        
        private RequestRelatedType requestRelatedField;
        
        private ReferenceType referenceField;
        
        private string policyNOField;
        
        /// <remarks/>
        public RequestRelatedType RequestRelated {
            get {
                return this.requestRelatedField;
            }
            set {
                this.requestRelatedField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string policyNO {
            get {
                return this.policyNOField;
            }
            set {
                this.policyNOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class ReferenceType {
        
        private string referIDField;
        
        private string referNOField;
        
        private string referMessageField;
        
        /// <remarks/>
        public string referID {
            get {
                return this.referIDField;
            }
            set {
                this.referIDField = value;
            }
        }
        
        /// <remarks/>
        public string referNO {
            get {
                return this.referNOField;
            }
            set {
                this.referNOField = value;
            }
        }
        
        /// <remarks/>
        public string referMessage {
            get {
                return this.referMessageField;
            }
            set {
                this.referMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
    public partial class queryGOTApolicyInfoRequestType : queryGOTApolicyInfoType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendTravelBizResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagementTypes/")]
    public partial class ReturnType {
        
        private string requestTypeField;
        
        private string responseCodeField;
        
        private string businessNoField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessNo {
            get {
                return this.businessNoField;
            }
            set {
                this.businessNoField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wss.nauw.ciod.ibm.com/ebusiness/thirdpartymanagement")]
    public partial class sendTravelBizResponseType : ReturnType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void sendTravelBizCompletedEventHandler(object sender, sendTravelBizCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendTravelBizCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendTravelBizCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendTravelBizResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendTravelBizResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void queryGOTApolicyInfoCompletedEventHandler(object sender, queryGOTApolicyInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryGOTApolicyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryGOTApolicyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public queryGOTApolicyInfoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((queryGOTApolicyInfoResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591